/* eslint-disable @typescript-eslint/no-explicit-any */

import type { AdminMenuItem } from "./types"

export const ADMIN_MENU: AdminMenuItem[] = [
  { key: "dashboard", icon: "📊", label: "Dashboard" },
  { key: "orders", icon: "📦", label: "Commandes" },
  { key: "items", icon: "🔫", label: "Boutique" },
  { key: "promo", icon: "💸", label: "Promotions" },
  { key: "banner", icon: "🖼", label: "Bannière" },
  { key: "auction", icon: "💰", label: "Enchères" },
  { key: "rewards", icon: "🎁", label: "Réductions" },
  { key: "buybacks", icon: "♻️", label: "Rachats" },
  { key: "users", icon: "👮", label: "Accès" },
  { key: "chat", icon: "💬", label: "Chat Staff" },
  { key: "logs", icon: "📜", label: "Logs" },
]

export const SAAS_THEME = {
  primary: "#00ffcc",
  background: "#07111a",
  surface: "#081018",
  card: "#0d1721",
  border: "rgba(0,255,204,.18)",
  danger: "#ff3b5c",
  warning: "#ffae00",
  success: "#00ff99",
}

export const styles: Record<string, any> = {
  loginPage: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: SAAS_THEME.background,
    color: "#fff",
  },
  shell: {
    display: "flex",
    minHeight: "100vh",
    background: SAAS_THEME.background,
    color: "#fff",
  },
  sidebar: {
    width: 260,
    padding: 18,
    borderRight: "1px solid rgba(0,255,204,.12)",
    background: SAAS_THEME.surface,
  },
  content: {
    flex: 1,
    padding: 20,
    overflowY: "auto",
    backgroundImage:
      "linear-gradient(rgba(0,255,204,.025) 1px, transparent 1px), linear-gradient(90deg, rgba(0,255,204,.025) 1px, transparent 1px)",
    backgroundSize: "24px 24px",
  },
  brand: {
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 18,
    color: SAAS_THEME.primary,
    textShadow: "0 0 12px rgba(0,255,204,.35)",
  },
  clock: {
    marginBottom: 18,
    opacity: 0.8,
  },
  card: {
    background: SAAS_THEME.card,
    border: `1px solid ${SAAS_THEME.border}`,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    color: "#fff",
    boxShadow: "0 0 18px rgba(0,255,204,.08)",
  },
  panelCard: {
    background: SAAS_THEME.card,
    border: `1px solid ${SAAS_THEME.border}`,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    color: "#fff",
  },
  panelHeader: {
    color: SAAS_THEME.primary,
    fontWeight: "bold",
    marginBottom: 12,
  },
  input: {
    width: "100%",
    maxWidth: "100%",
    boxSizing: "border-box",
    padding: 12,
    marginBottom: 12,
    borderRadius: 10,
    border: `1px solid ${SAAS_THEME.border}`,
    background: SAAS_THEME.surface,
    color: "#fff",
  },
  button: {
    padding: "10px 14px",
    borderRadius: 10,
    border: `1px solid ${SAAS_THEME.primary}`,
    background: "#00ffcc22",
    color: "#fff",
    cursor: "pointer",
    marginRight: 8,
    marginBottom: 8,
    fontWeight: "bold",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))",
    gap: 16,
  },
  inlineGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))",
    gap: 12,
  },
  row: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "center",
  },
  notif: {
    background: "#00ffcc22",
    border: `1px solid ${SAAS_THEME.primary}`,
    padding: 12,
    borderRadius: 12,
    marginBottom: 16,
    color: "#fff",
  },
  cardDanger: {
    border: `1px solid ${SAAS_THEME.danger}`,
    boxShadow: "0 0 18px rgba(255,59,92,.16)",
  },
  cardWarn: {
    border: `1px solid ${SAAS_THEME.warning}`,
    boxShadow: "0 0 18px rgba(255,174,0,.14)",
  },
  cardOk: {
    border: `1px solid ${SAAS_THEME.success}`,
  },
  sidebarButton: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    padding: "12px 14px",
    background: "#0f1720",
    border: "1px solid rgba(0,255,204,.12)",
    borderRadius: 10,
    color: "#fff",
    cursor: "pointer",
    marginBottom: 8,
    fontWeight: "bold",
  },
  sidebarButtonActive: {
    background: "linear-gradient(90deg,#00ffcc22,#00ffcc10)",
    border: `1px solid ${SAAS_THEME.primary}`,
  },
  sidebarBadge: {
    background: SAAS_THEME.danger,
    padding: "2px 8px",
    borderRadius: 999,
    fontSize: 12,
  },
  sidebarLogout: {
    width: "100%",
    padding: "12px 14px",
    background: "rgba(255,59,92,.12)",
    border: `1px solid ${SAAS_THEME.danger}`,
    borderRadius: 10,
    color: "#fff",
    cursor: "pointer",
    marginTop: 12,
    fontWeight: "bold",
  },
  statTitle: {
    opacity: 0.72,
    marginBottom: 8,
  },
  statValue: {
    color: SAAS_THEME.primary,
    fontSize: 28,
    fontWeight: "bold",
  },
  thumbnail: {
    width: 72,
    height: 72,
    objectFit: "cover",
    borderRadius: 10,
    border: `1px solid ${SAAS_THEME.primary}`,
    marginBottom: 10,
  },
}
